# Exercise 2B
Test some basic numpy functionality!

In [63]:
import numpy as np

### Numpy Arrays
Numpy arrays can be used to create number data collections and matrices.   
They offer lots of additional options exceeding python's list datatype.

**basic array creation**  
Python's lists can be converted by passing to constructor.

In [2]:
myList = [1,2,3,4,5,6,7,8,9,10]
myList

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [3]:
npArray = np.array(myList)
npArray

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
myMatrix = [[1,2,3],[4,5,6]]
myMatrix

[[1, 2, 3], [4, 5, 6]]

In [79]:
np.array(myMatrix)

array([[1, 2, 3],
       [4, 5, 6]])

**array from range**  
numpy.arange creates arrays from range parameters.

In [78]:
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [77]:
np.arange(0,11,2, dtype=int)

array([ 0,  2,  4,  6,  8, 10])

In [76]:
np.arange(0,11,2, dtype=float)

array([ 0.,  2.,  4.,  6.,  8., 10.])

**array standard helpers**

In [72]:
np.zeros(4)

array([0., 0., 0., 0.])

In [71]:
np.zeros((3,3), dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [70]:
np.ones((2,5), dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [25]:
np.eye(3,3, dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

**linespace**

In [88]:
# Creates an array with 12 values evenly spaced in between 2 and 24
np.linspace(2,24, num=12, dtype=int)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24])

**random**

In [74]:
# Creates 4 random values in range 0-1
np.random.rand(4)

array([0.57979483, 0.95195174, 0.80350343, 0.52031784])

In [83]:
# Creates a 2x2 matrix of random values.
np.random.rand(2,2)

array([[0.53050843, 0.93724714],
       [0.11045695, 0.97001501]])

In [81]:
np.random.randint(0, 50)

27